# This workflow will do a clean install of node dependencies and run tests.

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Integrate
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: npm install-ci-test
